### PR TITLE
feat: multiple tokens in ensurePermissions

### PR DESCRIPTION
**Pull request by gcandal**

### CODE REVIEW

**Comment by gcandal** [comment]
@joamag

**Comment by joamag** [comment]
@gcandal need rationale and precedent from appier on this one

**Comment by gcandal** [comment]
No precendent, didn't even realise this was ported from appier.

Rationale: there are some composite actions (e.g. listing of mixed resoures such as "config.cars" and "config.garages" in an endpoint such as `/configs`) which is weird to specify a single ACL token for. What would that token be? `configs`? It would be nice to go with `[config.cars.read, config.garages.read]`.

**Comment by joamag** [comment]
Closing this as not relevant.

**Pull request closed without merging**
