### PR TITLE
Created sizeRoundUnit method

### PR DESCRIPTION
**Pull request by NFSS10**
Converted [size_round_unit](https://github.com/hivesolutions/netius/blob/master/src/netius/common/util.py#L265) to Javascript and added it to `util.js`

<br>
Using the same unit tests as [test_size_round_unit](https://github.com/hivesolutions/netius/blob/2074ef2f274ab2ecacb93765f1b4e53bc7bbf5f6/src/netius/test/common/util.py#L125)

**Tests result:**
imagem

### CODE REVIEW

**Comment by gcandal** [comment]
@NFSS10 are there unit tests we can also port?

**Comment by NFSS10** [comment]
> @NFSS10 are there unit tests we can also port?

@gcandal Maybe this ? https://github.com/hivesolutions/netius/blob/2074ef2f274ab2ecacb93765f1b4e53bc7bbf5f6/src/netius/test/common/util.py#L125

**Comment by gcandal** [comment]
> > @NFSS10 are there unit tests we can also port?
> 
> @gcandal Maybe this ? https://github.com/hivesolutions/netius/blob/2074ef2f274ab2ecacb93765f1b4e53bc7bbf5f6/src/netius/test/common/util.py#L125

Touché 💪

**Comment by NFSS10** [comment]
> > > @NFSS10 are there unit tests we can also port?
> > 
> > 
> > @gcandal Maybe this ? https://github.com/hivesolutions/netius/blob/2074ef2f274ab2ecacb93765f1b4e53bc7bbf5f6/src/netius/test/common/util.py#L125
> 
> Touché 💪

@gcandal Added unit tests

**Comment by gcandal** [comment]
@joamag please take a look at this when you can.

**Review by joamag — APPROVED** [review]

**Pull request merged**
